account/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
#from auth import views as local_auth_views
from account import views as account_views

urlpatterns = [
    
    path('', account_views.index, name='index'),
    
    path('profile/', account_views.account_profile, name='account'),
    path('edit/', account_views.account_edit, name='account_edit'),
    path('register/', account_views.account_register, name='account_register'),
    
    path('login/', account_views.account_login, name='login'),
    path('logout/', account_views.account_logout, name='logout'),
    path('logout_then_login/', auth_views.logout_then_login, name='logoutthenlogin'),
    
    path('password-change/', auth_views.password_change, name='passwordchange'),
    path('password-change/done/', auth_views.password_change_done, name='password_change_done'),
    
    path('password-reset/', auth_views.password_reset, name='password_reset'),
    path('password-reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('password-confirm/(<uidb64>/<token>/', auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.password_reset_complete, name='password_reset_complete')
    
    
    ]

dynaplus/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('account.urls')),
    path('dynatag/', include('dynatag.urls')),
]

dynatag/urls.py
from __future__ import unicode_literals, absolute_import
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
#from auth import views as local_auth_views
from dynatag import  views as dynatag_views


from rest_framework import routers


app_name = 'dynatag'

router = routers.DefaultRouter()
router.register('users', dynatag_views.UserViewSet)
#router.register('userapps', dynatag_views.UserappViewSet)
router.register('applications', dynatag_views.ApplicationViewSet)
router.register('configurations', dynatag_views.ConfigurationViewSet)

urlpatterns = [
    
    path('', dynatag_views.main, name='dynatag_main'),
    path('appint/', dynatag_views.appint, name='dynatag_appint'),
    path('configuration/', dynatag_views.configuration, name='dynatag_configuration'),
    path('api/', include(router.urls)),
    #path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('appint/add/', dynatag_views.appint_add, name='dynatag_appint_add'),
    
    ]

dynatag/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User



# Create your models here.
'''
class Userapp(models.Model):    
    source = models.CharField(max_length=256, null=True)
    Authcontent = models.CharField(max_length=256, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
'''

class Masterdata(models.Model):
    clientid = models.CharField(max_length=256, null=True)
    clientsecret = models.CharField(max_length=256, null=True)
    redirecturl = models.CharField(max_length=256, null=True)
    responsetype = models.CharField(max_length=256, null=True)
    status = models.CharField(max_length=256, null=True)

class Application(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    appname = models.CharField(max_length=256, null=True)
    code = models.CharField(max_length=256, null=True)
    description = models.CharField(max_length=256, null=True)
    accesstoken =  models.CharField(max_length=256, null=True)
    refreshtoken =  models.CharField(max_length=256, null=True)
    tokenrefresh_time = models.DateTimeField(blank=True, null=True)
    appuri = models.CharField(max_length=256, null=True)
    status = models.CharField(max_length=256, null=True)
    errormessage = models.CharField(max_length=256, null=True)
    create_date = models.DateTimeField(blank=True, null=True)  
    
    def __unicode__(self):
        return self.appname 
     
class Configuration(models.Model):    
    confname = models.CharField(max_length=50, null=True)
    type = models.CharField(max_length=50, null=True)
    initalnum = models.IntegerField(null=True)
    actualnum = models.IntegerField(null=True)
    prefix = models.CharField(max_length=256, null=True)
    suffix = models.CharField(max_length=256, null=True)
    pstartdate = models.DateField(blank=True, null=True)
    penddate = models.DateField(blank=True, null=True)
    targetdate = models.DateField(blank=True, null=True)
    #user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    application = models.ForeignKey(Application, on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    
    def __unicode__(self):
        return self.confname
    

    
    
    
    

dynatag/views.py
from __future__ import  unicode_literals, absolute_import
from django.shortcuts import render
from .forms import UserRegForm, UserLoginForm
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from .models import Application, Configuration, Masterdata
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import authenticate, login, logout
from dynatag import urls
from dynaplus import settings as Settings


from rest_framework import permissions, viewsets
from rest_framework.decorators import ( permission_classes, detail_route)
from rest_framework.response import Response as Restresponse
from .serializers import UserSerializer, ConfigurationSerializer, ApplicationSerializer

from urllib.parse import urlencode
from urllib.request import Request, urlopen
import requests

# Create your views here.


def main(request):
    
    
    
    return render(request, 'main.html')

def appint(request):
    
    myappinfo = Masterdata.objects.get(status='active')
    content = {}
    content['clientid'] = myappinfo.clientid
    content['redirecturl'] = myappinfo.redirecturl
    content['responsetype'] = myappinfo.responsetype
    
    return render(request, 'appint.html', content)

def appint_add(request):
    
    content = {}
    c_code = content['code'] = request.GET.get('code')
    c_scope = content['scope'] = request.GET.get('scope').split('|')[0]
    c_appname = content['appname'] = request.GET.get('scope').split('|')[1]
    content['state'] = request.GET.get('state')
    
    try:
        u_user = User.objects.get(username = 'test')
    except Application.DoesNotExist:
        u_user = None
    
    try:
        u_app = Application.objects.get(appname = c_appname, status = 'active', user=u_user)
    except Application.DoesNotExist:
        u_app = None
    
    if u_app:
        
        u_app.code = c_code
        u_app.scope = c_scope
        u_app.save()
        
    else:
        u_app = Application.objects.create()
        u_app.user = u_user
        u_app.appname = c_appname
        u_app.code = c_code
        u_app.scope = c_scope
        u_app.save()
    
    #send post request to get access token
    myappinfo = Masterdata.objects.get(status='active')
    s_url = 'https://api.infusionsoft.com/token'
    
    s_client_id = myappinfo.clientid
    s_client_secret = myappinfo.clientsecret
    s_code = c_code
    s_grant_type = 'authorization_code'
    s_redirect_uri = myappinfo.redirecturl + 'gettoken/'
    post_field = {
        
        'client_id': s_client_id,
        'client_secret': s_client_secret,
        'code': s_code,
        'grant_type': s_grant_type,
        'redirect_uri': s_redirect_uri, 
        
        }
    
    result = requests.post(s_url, post_field)
    #result = urlopen(request).read().decode()
    
    return HttpResponse(result)

def configuration(request):
    
    
    
    return render(request, 'configuration.html')

class UserViewSet(viewsets.ModelViewSet):
    
    queryset = User.objects.all()
    serializer_class = UserSerializer

'''    
class UserappViewSet(viewsets.ModelViewSet):
    
    queryset = Userapp.objects.all()
    serializer_class = UserappSerializer
'''
    
class ApplicationViewSet(viewsets.ModelViewSet):
    
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer  
          
class ConfigurationViewSet(viewsets.ModelViewSet):
    
    queryset = Configuration.objects.all()
    serializer_class = ConfigurationSerializer
    

    

dynatag/templates/includes/dynatag_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %} {% endblock %}</title>
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "css/dashboard.css" %}" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
          	
            <li class="active"><a href="{% url 'dynatag:dynatag_main' %}">Overview</a></li>
            <li><a href="{% url 'dynatag:dynatag_appint' %}">App Integration</a></li>
            <li><a href="{% url 'dynatag:dynatag_configuration' %}">Configuration</a></li>
            
          </ul>
          <!--
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
          -->
        </div>
        {% block content %}
        
    	{% endblock %}
      </div>
    </div>

    <script src="{% static "js/jquery-3.2.1.min.js" %}" ></script>
	<script src="{% static "js/bootstrap.min.js" %}" ></script>
	<script src="{% static "js/angular.min.js" %}" ></script>
	<script src="{% static "js/dynaplus.js" %}"></script>
	
    
</body>

</html>